const watchInventory = [
    {
        brand: "CASIO",
        name: "CASIO MENS GOLD MTP B145G 9A",
        price: 6360,
        discount: 20,
        img: "MTP-B145G-9A.png",
        movement: "Analog",
        caseSize: "40 × 35 × 7.4 mm",
        material: "Gold Ion Plated",
        waterRes: "50-meter",
        battery: "SR621SW",	
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-B145G-9AV/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS GOLD MTP VD03G 1A",
        price: 2899,
        discount: 20,
        img: "MTP-VD03G-1A.png",
        movement: "Analog",
        caseSize: "48 × 41 × 9.6 mm",
        material: "Gold tone",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VD03G-1A/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS GOLD MTP VD200G 1B",
        price: 3199,
        discount: 20,
        img: "MTP-VD200G-1B.png",
        img2: "MTP-VD200G-1B-2.png",		
        movement: "Analog",
        caseSize: "49 × 45 × 8.7 mm",
        material: "Gold tone",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VD200G-1B/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP VD01D 3E2",
        price: 3199,
        discount: 20,
        img: "MTP-VD01D-3E2.png",
        movement: "Analog",
        caseSize: "49 × 45 × 10.3 mm",
        material: "Silver tone",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VD01D-3E2V/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS TWO TONE MTP VD300SG 1E",
        price: 4199,
        discount: 20,
        img: "MTP-VD300SG-1E.png",
		img2: "VD300SG-1E-2.png",
        movement: "Analog",
        caseSize: "49 × 45 × 8.7 mm",
        material: "Two-tone Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.casio.com/ph/watches/casio/"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS GOLD SNKK20K1",
        price: 10799,
        discount: 10,
        img: "SNKK20K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Gold-Plated",
        waterRes: "30m",
        battery: "Kinetic",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-snkk20k1"
    },
	{
        brand: "SEIKO",
        name: "SEIKO SNKP09K1 MENS SILVER",
        price: 9699, // Palitan mo ito ng iyong actual price
        discount: 10, // Palitan mo kung ilang % ang discount
        img: "SNKP09K1.png",
        movement: "Automatic (7S26)",
        caseSize: "42mm Diameter",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/classic-snkp09k1?srsltid=AfmBOoq-LjSyiOpNM7LtzV1yZRBtPDemrePGc6PyvtVX3ZR7E2-9_Kvw&variant=47927734993177"
    },
	{
        brand: "SEIKO",
        name: "SEIKO MENS SILVER SNK371K1",
        price: 9099,
        discount: 10,
        img: "SNK371K1.png",
        movement: "Automatic (7S26)",
        caseSize: "37mm Diameter",
        material: "Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.creationwatches.com/products/seiko-mens-watches-208/seiko-5-automatic-21-jewels-snk371-snk371k1-snk371k-mens-watch-5931.html"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS TWO TONE SNKE54K1",
        price: 9299,
        discount: 10,
        img: "SNKE54K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Two-tone Steel (Gold/Silver)",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/classic-snke04k1?_pos=1&_psq=SNKE54K1&_ss=e&_v=1.0&variant=45518680293657"
    },
	{
        brand: "SEIKO",
        name: "SEIKO MENS SILVER SNKK31K1",
        price: 9099,
        discount: 10,
        img: "SNKK31K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS GOLD SNKL50K1",
        price: 9299,
        discount: 10,
        img: "SNKL50K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Gold-Plated Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-snkl50k1-automatic-gold-plated-stainless-steel-watch-for-men"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SILVER SNKK13K1",
        price: 9099,
        discount: 10,
        img: "SNKK13K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports"
    },
	{
        brand: "SEIKO",
        name: "SEIKO MENS SILVER SNKL17K1",
        price: 9099,
        discount: 10,
        img: "SNKL17K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-5-snkl47k1-silver-stainless-automatic-watch-men"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS GOLD SNKL64K1",
        price: 9299,
        discount: 10,
        img: "SNKL64K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Gold-Plated Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-5-sports-snkl64k1-gold-stainless-automatic-watch-for-men"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MEN’S TWO TONE SNKL62K1",
        price: 9199,
        discount: 10,
        img: "SNKL62K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Two-tone Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS TWO TONE SNKL36K1",
        price: 9299,
        discount: 10,
        img: "SNKL36K1.png",
		img2: "SNKL36K1-2.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Two-tone Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-snkl36k1-automatic-two-tone-stainless-steel-watch-for-men"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS GOLD SNKK86K1",
        price: 9299,
        discount: 10,
        img: "SNKK86K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Gold-Plated Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-snkk86k1-automatic-gold-plated-stainless-steel-watch-for-men"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS GOLD SNKL40K1",
        price: 9299,
        discount: 10,
        img: "SNKL40K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Gold-Plated Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-5-sports-snkl40k1-automatic-watch-for-men"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS GOLD SNKL58K1",
        price: 9299,
        discount: 10,
        img: "SNKL58K1.png",
        movement: "Automatic (7S26)",
        caseSize: "38mm Diameter",
        material: "Gold-Plated Stainless Steel",
        waterRes: "30-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.watchportal.com.ph/products/seiko-5-snkl58k1-gold-stainless-automatic-watch-men"
    },
	{
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPD63K1",
        price: 15767.50,
        discount: 10,
        img: "SRPD63K1.png",
        img2: "SRPD63K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://timedepot.com.ph/products/srpd63k1"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPG29K1",
        price: 15767.50,
        discount: 10,
        img: "SRPG29K1.png",
        img2: "SRPG29K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "39.4mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-srpg29k1"
    },
    {
        brand: "SEIKO",
        name: "Seiko 5 Sports SRPF65K1 NARUTO Limited",
        price: 20000,
        discount: 0, // Under Negotiation
        img: "SRPF65K1.png",
        img2: "SRPF65K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Limited Edition (Boruto Uzumaki)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-srpf65k1-naruto-boruto-limited-edition"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPF70K1 NARUTO",
        price: 20500,
        discount: 0, // Under Negotiation
        img: "SRPF70K1.png",
        img2: "SRPF70K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel (Gold Coating)",
        waterRes: "100-meter",
        battery: "Limited Edition (Naruto Uzumaki)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports/srpf70"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPF67K1 SARADA",
        price: 20500,
        discount: 0, // Under Negotiation
        img: "SRPF67K1.png",
        img2: "SRPF67K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Limited Edition (Sarada Uchiha)",
        fullSpecs: "https://www.seikowatches.com/nz-en/products/5sports/special/naruto_boruto/sarada.html"
    },
    {
        brand: "SEIKO",
        name: "Seiko 5 Sports SRPE51K1 Silver Automatic",
        price: 14790,
        discount: 10,
        img: "SRPE51K1.png",
        img2: "SRPE51K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "40mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://timedepot.com.ph/products/srpe51k1"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPD85K1",
        price: 16199,
        discount: 10,
        img: "SRPD85K1.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel (Brown Coating)",
        waterRes: "100-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-srpd85k1"
    },
    {
        brand: "SEIKO",
        name: "Seiko 5 SRPF23K1 Street Fighter BLANKA",
        price: 18899,
        discount: 0, 
        img: "SRPF23K1.png",
        img2: "SRPF23K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Limited Edition (Street Fighter V)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports/special/streetfighter/"
    },
	{
        brand: "SEIKO",
        name: "SEIKO MENS SPORT SNZG11K1 BLUE",
        price: 10899,
        discount: 10,
        img: "SNZG11K1.png",
        img2: "SNZG11K1-2.png",
        movement: "Automatic (7S36)",
        caseSize: "42mm Diameter",
        material: "Stainless Steel / Nylon Strap",
        waterRes: "100-meter",
        battery: "Self-Winding (Kinetic)",
        fullSpecs: "https://www.chrono24.ph/seiko/5-sports-snzg11-blue-military-mens-watch-automatic-nylon-strap--id38100766.htm"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPD57K1",
        price: 13899,
        discount: 10,
        img: "SRPD57K1.png",
        img2: "SRPD57K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-srpd57k1"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPD55K1",
        price: 16199,
        discount: 10,
        img: "SRPD55K1.png",
        img2: "SRPD55K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://www.discovery-japan.me/category/select/pid/9026"
    },
	{
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPD65K1",
        price: 16599,
        discount: 10,
        img: "SRPD65K1.png",
        img2: "SRPD65K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Hard Coated Stainless Steel (Black)",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports/srpd65"
    },
    {
        brand: "SEIKO",
        name: "SEIKO MENS SPORTS 100M SRPD51K1",
        price: 15000,
        discount: 10,
        img: "SRPD51K1.png",
        img2: "SRPD51K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://www.seikowatches.com/ph-en/products/5sports/srpd51"
    },
    {
        brand: "SEIKO",
        name: "SEIKO SRPD71K1 NEW 5 MENS SPORTS",
        price: 16199,
        discount: 10,
        img: "SRPD71K1.png",
        img2: "SRPD71K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Stainless Steel / Mesh Bracelet",
        waterRes: "100-meter",
        battery: "Self-Winding (41 Hours Power Reserve)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-srpd71k1"
    },
    {
        brand: "SEIKO",
        name: "SEIKO SRPF75K1 SHIKAMARU Limited Edition",
        price: 20000,
        discount: 10,
        img: "SRPF75K1.png",
        img2: "SRPF75K1-2.png",
        movement: "Automatic (4R36)",
        caseSize: "42.5mm Diameter",
        material: "Hard Coated Stainless Steel",
        waterRes: "100-meter",
        battery: "Limited Edition (Shikamaru Nara)",
        fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-srpf75k1-naruto-boruto-limited-edition"
    },
	{
        brand: "CASIO",
        name: "CASIO MENS TWO TONE MTP 1303SG 7A",
        price: 4014,
        discount: 20,
        img: "MTP-1303SG-7A.png",
        img2: "MTP-1303SG-7A-2.png",
        movement: "Quartz",
        caseSize: "47 × 40 × 8.1 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-1303sg-7avdf-two-tone-stainless-steel-strap-watch-for-men"
    },
    {
        brand: "CASIO",
        name: "Casio Vintage LTP-1128G-9AR Gold Women",
        price: 2862,
        discount: 20,
        img: "LTP-1128G-9A.png",
        img2: "LTP-1128G-9A-2.png",
        movement: "Quartz",
        caseSize: "33 × 28.5 × 7 mm",
        material: "Gold/Silver Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.casio.com/ph/watches/casio/"
    },
    {
        brand: "CASIO",
        name: "CASIO LADIES TWO TONE LTP 1128G 7B",
        price: 2899,
        discount: 20,
        img: "LTP-1128G-7B.png",
        img2: "LTP-1128G-7B-2.png",
        movement: "Quartz",
        caseSize: "33 × 28.5 × 7 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.casio.com/ph/watches/casio/"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-1314SG-1AVDF Two Tone Men",
        price: 4257,
        discount: 20,
        img: "MTP-1314SG-1A.png",
        img2: "MTP-1314SG-1A-2.png",
        movement: "Quartz",
        caseSize: "50 × 44.9 × 9.4 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-1314sg-1avdf-two-tone-stainless-steel-strap-watch-for-men"
    },
    {
        brand: "CASIO",
        name: "Casio LTP-1235SG-7ADF Two tone Women",
        price: 3294,
        discount: 20,
        img: "LTP-1235SG-7A.png",
        img2: "LTP-1235SG-7A-2.png",
        movement: "Quartz",
        caseSize: "28.5 × 20.5 × 8.2 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-ltp-1235sg-7adf-two-tone-stainless-steel-watch-for-women"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-1183G-7ADF Two Tone Men",
        price: 3501,
        discount: 20,
        img: "MTP-1183G-7ADF.png",
        img2: "MTP-1183G-7ADF-2.png",
        movement: "Quartz",
        caseSize: "42 × 38.5 × 8.7 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-1183g-7adf-two-tone-stainless-steel-strap-watch-for-men"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-1308SG-7AVDF Two Tone Men",
        price: 4257,
        discount: 20,
        img: "MTP-1308SG-7AVDF.png",
        img2: "MTP-1308SG-7AVDF-2.png",
        movement: "Quartz",
        caseSize: "48.9 × 43.5 × 9.2 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-1308sg-7avdf-two-tone-stainless-steel-strap-watch-for-men"
    },
    {
        brand: "CASIO",
        name: "Casio LTP-1170G-7A Silver Stainless Women",
        price: 3078,
        discount: 20,
        img: "LTP-1170G-7A.png",
        img2: "LTP-1170G-7A-2.png",
        movement: "Quartz",
        caseSize: "33 × 28.5 × 7.3 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-ltp-1170g-7a-silver-stainless-steel-strap-watch-for-women-1"
    },
    {
        brand: "CASIO",
        name: "Casio LTP-1314SG-1AVDF Two Tone Women",
        price: 4257,
        discount: 20,
        img: "LTP-1314SG-1AVDF.png",
        img2: "LTP-1314SG-1AVDF-2.png",
        movement: "Quartz",
        caseSize: "36.5 × 33.1 × 8.8 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-ltp-1314sg-1avdf-two-tone-stainless-steel-strap-watch-for-women"
    },
    {
        brand: "CASIO",
        name: "Casio LTP-1275SG-7BDF Two Tone Women",
        price: 3177,
        discount: 20,
        img: "LTP-1275SG-7BDF.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "30 × 25 × 6.7 mm",
        material: "Two-tone Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-ltp-1275sg-7bdf-two-tone-stainless-steel-strap-watch-for-women"
    },
	{
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP B145D 9A",
        price: 5090,
        discount: 20,
        img: "MTP-B145D-9A.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "40 × 35 × 7.4 mm",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "SR621SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-B145D-9AV/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP VD03D 2A2",
        price: 3170,
        discount: 20,
        img: "MTP-VD03D-2A2.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "45 × 38 × 9.4 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VD03D-2A2/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP B145D 4A",
        price: 5090,
        discount: 20,
        img: "MTP-B145D-4A.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "40 × 35 × 7.4 mm",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "SR621SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-B145D-4AV/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTD 125D 2A2",
        price: 8060,
        discount: 20,
        img: "MTD-125D-2A2.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "46.5 × 45.6 × 10.4 mm",
        material: "Stainless Steel / Anti-reverse Bezel",
        waterRes: "100-meter",
        battery: "SR920SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTD-125D-2A2V/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP VD03D 3A2",
        price: 3170,
        discount: 20,
        img: "MTP-VD03D-3A2.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "45 × 38 × 9.4 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VD03D-3A2/"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-1308D-1A2VDF Silver Men",
        price: 3330,
        discount: 20,
        img: "MTP-1308D-1A2VDF.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "48.9 × 43.5 × 9.2 mm",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-1308d-1a2vdf-silver-stainless-steel-strap-watch-for-men"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP E600B 2B",
        price: 6880,
        discount: 20,
        img: "MTP-E600B-2B.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "49 × 41 × 8.5 mm",
        material: "Stainless Steel (Black IP)",
        waterRes: "50-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-E600B-2B/"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-VT01D-2B Silver Watch Men",
        price: 2890,
        discount: 20,
        img: "MTP-VT01D-2B.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "46 × 40 × 8.2 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VT01D-2B/"
    },
    {
        brand: "CASIO",
        name: "CASIO LADIES SILVER LTP V006D 7B2",
        price: 2330,
        discount: 20,
        img: "LTP-V006D-7B2.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "30.4 × 25 × 9.2 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.LTP-V006D-7B2/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MDV 107D 3A STARBUCKS",
        price: 7420,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "49.5 × 44.2 × 12.1 mm",
        material: "Stainless Steel / Green Bezel",
        waterRes: "200-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MDV-107D-3AV/"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-E150D-7B Silver Watch Men",
        price: 6680,
        discount: 30,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "47 × 40 × 9.5 mm",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-e150d-7b-silver-stainless-watch-for-men"
    },
    {
        brand: "CASIO",
        name: "Casio AQ-230A-2A1MQYDF Dig-Ana Silver",
        price: 3320,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Digital-Analog",
        caseSize: "38.8 × 29.8 × 8.1 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR920W (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-aq-230a-2a1mqydf-digital-analog-stainless-steel-strap-watch"
    },
    {
        brand: "CASIO",
        name: "Casio LTP-1170A-2ARDF Silver Women",
        price: 2830,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "33 × 28.5 × 7.3 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-ltp-1170a-2ardf-silver-stainless-watch-for-women-1"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP VT01D 2B2",
        price: 3000,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "46 × 40 × 8.2 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-VT01D-2B2/"
    },
    {
        brand: "CASIO",
        name: "Casio LTP-1303D-7BVDF Silver Women",
        price: 3060,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "35.5 × 30 × 7.5 mm",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-ltp-1303d-7bvdf-silver-stainless-steel-strap-watch-for-women"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS BLACK MTP B115B 1E",
        price: 4000,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "48 × 41 × 8 mm",
        material: "Stainless Steel (Black IP)",
        waterRes: "50-meter",
        battery: "SR621SW (3 Years)",
        fullSpecs: "https://www.casio.com/intl/watches/casio/product.MTP-B115B-1EV/"
    },
    {
        brand: "CASIO",
        name: "CASIO MENS SILVER MTP V002D 2B3",
        price: 2240,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "44 × 37 × 9.6 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-V002D-2B3/"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-1183A-7BDF Silver Men",
        price: 2830,
        discount: 20,
        img: "soon.png",
        img2: "soon.png",
        movement: "Quartz",
        caseSize: "42 × 38.5 × 8.7 mm",
        material: "Stainless Steel",
        waterRes: "Water Resistant",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.casio.com/ph/watches/casio/product.MTP-1183A-2A/"
    },
    {
        brand: "CASIO",
        name: "Casio MTP-1303D-7AVDF Silver Men",
        price: 3060,
        discount: 20,
        img: "MTP-1303D-7AVDF.png",
        img2: "MTP-1303D-7AVDF-2.png",
        movement: "Quartz",
        caseSize: "47 × 40 × 8.1 mm",
        material: "Stainless Steel",
        waterRes: "50-meter",
        battery: "SR626SW (3 Years)",
        fullSpecs: "https://www.watchportal.com.ph/products/casio-mtp-1303d-7avdf-silver-stainless-steel-strap-watch-for-men"
    },
	{
    name: "SEIKO MENS SPORTS SSK023K1",
    model: "SSK023K1",
    price: 20000,
    discount: 10,
    img: "ssk023k1.png", // Siguraduhing i-upload ang image na ito sa GitHub
    img2: "ssk023k1-2.png",
    movement: "4R34 Automatic with GMT",
    caseSize: "39.4 mm x 13.1 mm",
    material: "Stainless Steel",
    waterRes: "10 bar (100m)",
    fullSpecs: "https://shop.seikoboutique.com.ph/products/seiko-5-sports-ssk023k1"
	}
	
	
];
